# Assignment - Numpy

In [1]:
#1
#A Python library is a collection of pre-written code and functionalities that can be imported and used in Python programs to perform specific tasks. 
#We use Python libraries to leverage existing solutions, saving time and effort by avoiding the need to reinvent the wheel for common programming tasks.

In [2]:
#2
#Numpy arrays are homogeneous data structures, meaning they store elements of the same data type, and offer more efficient computation and storage due 
#to their fixed size and pre-allocated memory. Lists, on the other hand, are heterogeneous and can contain elements of different data types, but they 
#are less efficient for numerical computations and lack many of the specialized operations available in Numpy arrays.

In [3]:
#3
#Shape: 3 rows, 4 columns
#Size: 3 * 4 = 12 elements
#Dimension: 2 dimensions

In [13]:
#4
arr=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
first_row=arr[0]
print(first_row)

[1, 2, 3, 4]


In [10]:
#5
import numpy as np
arr=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
arr=np.array(arr)
element=arr[2,3]
print(element)

12


In [16]:
#6
import numpy as np
arr=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
arr=np.array(arr)
odd_indexed=arr[1::2,1::2]
print(odd_indexed)

[[6 8]]


In [2]:
#7
import numpy as np
np.random.random((3,3))

array([[0.77259386, 0.7590355 , 0.88846463],
       [0.18150352, 0.49229306, 0.9990882 ],
       [0.37648282, 0.93509788, 0.03418017]])

In [3]:
#8
#`np.random.rand` generates an array of specified shape with random values uniformly distributed between 0 and 1. `np.random.randn` generates an array of 
#specified shape with random values drawn from a standard normal distribution (mean=0, standard deviation=1).

In [5]:
#9
import numpy as np
arr=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
arr=np.array(arr)
np.expand_dims(arr,axis=2)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [6]:
#10
import numpy as np
arr=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
arr=np.array(arr)
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [10]:
#11
import numpy as np
Matrix_A=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
Matrix_B=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [11]:
#11.1
Matrix_A*Matrix_B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [14]:
#11.2
Matrix_A@Matrix_B.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [15]:
#11.3
Matrix_A+Matrix_B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [16]:
#11.4
Matrix_A-Matrix_B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
#11.5
Matrix_B/Matrix_A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
#12
#The `byteswap()` function in NumPy can be used to swap the byte order of an array.

In [19]:
#13
#The `np.linalg.inv` function in NumPy calculates the inverse of a square matrix. It's significant because it allows for solving systems of linear 
#equations, matrix equations, and finding solutions to various mathematical problems involving matrices, such as least squares regression and eigenvalue problems.

In [23]:
#14
#The `np.reshape` function in NumPy is used to change the shape of an array without changing its data. It allows you to rearrange the elements of the 
#array into a new shape specified by the user, as long as the total number of elements remains constant.

#Usage:

import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6])
reshaped_arr=np.reshape(arr, (2, 3))
print("Original array:")
print(arr)
print("Reshaped array:")
print(reshaped_arr)

Original array:
[1 2 3 4 5 6]
Reshaped array:
[[1 2 3]
 [4 5 6]]


In [24]:
#15
#Broadcasting in NumPy is a mechanism that allows arrays of different shapes to be combined in arithmetic operations. It automatically aligns dimensions 
#of arrays when performing element-wise operations, making computations more efficient and concise.